{
    "name": "Impress Quality Worksheets",
    "version": "17.0.26.01.22",
    "summary": """ Worksheets to use in conjunction with Impress Quality Logs """,
    "author": "Cédric Paradis",
    "website": "https://github.com/Impress-Foods/impress-odoo",
    "category": " Hidden",
    "depends": [
        "base",
        "impress_quality_logs",
        "worksheet",
        "quality_control_worksheet",
    ],
    "data": [
        "data/weight/WeightWorksheet_20250203.xml",
        "views/weight/WeightWorksheet_20250203.xml",
        "data/HPP/HPPWorksheet_20250203.xml",
        "views/HPP/HPPWorksheet_20250203.xml",
        "data/metal/MetalWorksheet_20250203.xml",
        "views/metal/MetalWorksheet_20250203.xml",
        "data/coding/CodingWorksheet_20250303.xml",
        "views/coding/CodingWorksheet_20250303.xml",
        "data/xray/XrayWorksheet_20250303.xml",
        "views/xray/XrayWorksheet_20250303.xml",
        "data/xray/XrayWorksheet_large_20251126.xml",
        "views/xray/XrayWorksheet_large_20251126.xml",
    ],
    "installable": True,
    "license": "GPL-2",
}
