{
    "name": "Manufacturing Automation",
    "version": "17.0.1.0.0",
    "summary": """ Addon to automatize part of the manufacturing process """,
    "author": "Cédric Paradis",
    "website": "https://github.com/Impress-Foods/impress-odoo",
    "category": "Hidden",
    "depends": ["base", "mrp", "stock", "mrp_fast_allocation"],
    "data": [
        "data/mrp_campaign_sequence.xml",
        "security/ir.model.access.csv",
        "security/mrp_campaign_rules.xml",
        "wizards/mrp_campaign_creator_views.xml",
        "wizards/mrp_campaign_add_demand_views.xml",
        "wizards/mrp_campaign_split_views.xml",
        "views/mrp_campaign_views.xml",
        "views/mrp_production_views.xml",
        "views/product_views.xml",
        "reports/mrp_campaign_report.xml",
    ],
    "assets": {
        "web.assets_backend": ["mrp_campaign/static/src/**/*"],
    },
    "installable": True,
    "license": "GPL-2",
}
