from .test_wizard_campaign_creator import TestMrpCampaignCreatorDirect
from .test_wizard_add_demand import TestMrpCampaignAddDemand
from .test_wizard_partition import TestMrpCampaignPartition
from .test_stock_move import TestStockMove
from .test_mrp_campaign_torture import TestMrpCampaignTorture
