{
    "name": "Theme A+",
    "version": "17.0.1.0.0",
    "summary": """ A+ Theme """,
    "author": "Cédric Paradis",
    "website": "https://github.com/Impress-Foods/impress-odoo",
    "category": "Theme/Website",
    "depends": ["web", "website", "website_sale"],
    "data": [
        "views/vectors.xml",
        "security/ir.model.access.csv",
        "views/snippets/s_dynamic_content.xml",
        "data/shapes.xml",
        "views/product_card.xml",
        "views/product_template_views.xml",
        "views/shop_templates.xml",
        "views/snippets/s_dynamic_snippet_product_templates.xml",
        "views/snippets/s_window_carousel.xml",
        "views/snippets/options.xml",
        "views/snippets/s_scrolling_banner.xml",
        "views/snippets/s_wave_transition.xml",
        "views/snippets/templates.xml",
        "data/pages/landing_page.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            "theme_aplus/static/src/scss/_fonts.scss",
            "theme_aplus/static/src/scss/_aplus_colors.scss",
            "theme_aplus/static/src/scss/primary_variables.scss",
        ],
        "web.assets_frontend": [
            "theme_aplus/static/src/snippets/s_wave_transition/000.js",
            "theme_aplus/static/src/snippets/s_wave_transition/000.scss",
            "theme_aplus/static/src/snippets/s_wave_transition/000.xml",
            "theme_aplus/static/src/snippets/s_scrolling_banner/000.scss",
            "theme_aplus/static/src/snippets/s_scrolling_banner/000.xml",
            "theme_aplus/static/src/snippets/s_scrolling_banner/000.js",
            "theme_aplus/static/src/snippets/s_window_carousel/000.xml",
            "theme_aplus/static/src/snippets/s_window_carousel/000.js",
            "theme_aplus/static/src/snippets/s_window_carousel/000.scss",
            "theme_aplus/static/src/snippets/s_dynamic_snippet_product_templates/000.scss",
            "theme_aplus/static/src/snippets/s_dynamic_snippet_product_templates/000.js",
            "theme_aplus/static/src/snippets/s_dynamic_snippet_product_templates/000.xml",
            "theme_aplus/static/src/scss/aplus_style.scss",
            "theme_aplus/static/src/scss/ecom.scss",
            "theme_aplus/static/src/js/website_sale.js",
            "theme_aplus/static/src/scss/product_page.scss",
        ],
        "website.assets_wysiwyg": [
            "theme_aplus/static/src/scss/aplus_style.scss",
            "theme_aplus/static/src/scss/ecom.scss",
            "theme_aplus/static/src/snippets/s_scrolling_banner/options.js",
            "theme_aplus/static/src/snippets/s_dynamic_snippet_product_templates/options.js",
            "theme_aplus/static/src/snippets/s_window_carousel/options.js",
        ],
    },
    "application": False,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
