{
    "name": "Theme A+",
    "version": "19.0.1.0.0",
    "summary": """ A+ Theme """,
    "author": "Cédric Paradis",
    "website": "https://github.com/Impress-Foods/impress-odoo",
    "category": "Theme/Website",
    "depends": ["web", "website", "website_sale"],
    "data": [
        "data/data.xml",
        "views/filters.xml",
        "views/vectors.xml",
        "security/ir.model.access.csv",
        "views/snippets/s_dynamic_content.xml",
        "data/shapes.xml",
        "views/product_card.xml",
        "views/product_template_views.xml",
        "views/shop_templates.xml",
        "views/snippets/s_window_carousel.xml",
        "views/snippets/s_image_marquee.xml",
        "views/snippets/snippets.xml",
        "views/snippets/s_wave_transition.xml",
        "views/snippets/templates.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            "theme_aplus/static/src/scss/_fonts.scss",
            "theme_aplus/static/src/scss/_aplus_colors.scss",
            "theme_aplus/static/src/scss/primary_variables.scss",
        ],
        "web.assets_frontend": [
            "theme_aplus/static/src/snippets/s_wave_transition/000.scss",
            "theme_aplus/static/src/snippets/s_window_carousel/000.xml",
            "theme_aplus/static/src/snippets/s_window_carousel/000.js",
            "theme_aplus/static/src/snippets/s_window_carousel/000.scss",
            "theme_aplus/static/src/snippets/s_image_marquee/000.scss",
            "theme_aplus/static/src/snippets/s_image_marquee/000.js",
            "theme_aplus/static/src/scss/aplus_style.scss",
            "theme_aplus/static/src/scss/ecom.scss",
            "theme_aplus/static/src/scss/minimalist_cards.scss",
            "theme_aplus/static/src/scss/product_page.scss",
            "theme_aplus/static/src/scss/tabbed_container.scss",
            "theme_aplus/static/src/js/website_sale.js",
        ],
        "website.website_builder_assets": [
            "theme_aplus/static/src/website_builder/wave_transition_option.js",
            "theme_aplus/static/src/website_builder/wave_transition_option.xml",
            "theme_aplus/static/src/website_builder/window_carousel_option.js",
            "theme_aplus/static/src/website_builder/window_carousel_option.xml",
            "theme_aplus/static/src/website_builder/image_marquee_option.js",
            "theme_aplus/static/src/website_builder/image_marquee_option.xml",
            "theme_aplus/static/src/website_builder/product_page_option.js",
            "theme_aplus/static/src/website_builder/product_page_option.xml",
        ],
    },
    "application": False,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
