from . import mrp_campaign
from . import mrp_campaign_demand
from . import mrp_campaign_line
from . import mrp_production
from . import mrp_workorder
from . import procurement
from . import product_template
from . import stock_move
from . import stock_rule
