{
    "name": "Impress Quality Logs",
    "version": "19.0.1.0.1",
    "summary": """ Implements many quality logs used by
    Impress Foods for quality control """,
    "author": "Cédric Paradis",
    "website": "https://github.com/Impress-Foods/impress-odoo",
    "category": "Manufacturing",
    "depends": [
        "mrp_workorder",
        "sign",
        "quality_mrp_workorder_worksheet",
        "product_expiry",
        "quality_control_worksheet",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/actions.xml",
        "views/hpp_log_views.xml",
        "views/hpp_log_line_views.xml",
        "views/metal_log_views.xml",
        "views/metal_log_line_views.xml",
        "views/coding_log_views.xml",
        "views/product_product_views.xml",
        "views/weight_log_line_views.xml",
        "views/weight_log_views.xml",
        "views/mrp_production_views.xml",
        "views/x_ray_log_views.xml",
        "views/x_ray_log_line_views.xml",
        "views/menus.xml",
        "views/worksheet_log_type_views.xml",
        "views/quality_point_views.xml",
        "views/worksheet_template_views.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "GPL-2",
}
