{
    "name": "Impress Quality Logs",
    "version": "17.0.0.1.4",
    "summary": """ Implements many quality logs used by ^
    Impress Foods for quality control """,
    "author": "Cédric Paradis",
    "website": "https://github.com/Impress-Foods/impress-odoo",
    "category": "Manufacturing",
    "depends": [
        "base",
        "web",
        "stock",
        "quality_mrp",
        "mrp_workorder",
        "sign",
        "quality_mrp_workorder_worksheet",
        "product_expiry",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/actions.xml",
        "views/hpp_log_views.xml",
        "views/hpp_log_line_views.xml",
        "views/loma_log_views.xml",
        "views/loma_log_line_views.xml",
        "views/metal_log_views.xml",
        "views/metal_log_line_views.xml",
        "views/coding_log_views.xml",
        "views/product_product_views.xml",
        "views/mrp_production_views.xml",
        "views/x_ray_log_views.xml",
        "views/x_ray_log_line_views.xml",
        "views/menus.xml",
        "reports/quality_log_report_views.xml",
        "reports/hpp_log_report.xml",
        "reports/loma_log_report.xml",
        "reports/coding_log_report.xml",
        "reports/metal_log_report.xml",
        "reports/xray_log_report.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "GPL-2",
}
