{
    "name": "impress_production_billing",
    "version": "19.0.0.1.2",
    "summary": """ Module to allow billing of MOs directly through SOs """,
    "author": "Cédric Paradis",
    "website": "https://github.com/Impress-Foods/impress-odoo",
    "category": "Sales",
    "depends": ["mrp", "purchase", "sale_management", "portal", "product_expiry"],
    "data": [
        "security/impress_production_billing_security.xml",
        "security/ir.model.access.csv",
        "views/mrp_bom_views.xml",
        "views/mrp_production_views.xml",
        "views/portal/portal_production.xml",
        "views/portal/portal_sale_order_views.xml",
        "views/sale_order_views.xml",
    ],
    "installable": True,
    "license": "GPL-2",
}
